//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazadaLatest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductCart
    {
        public int Id { get; set; }

        [Display(Name = "Product ID")]
        public Nullable<int> productId { get; set; }

        [Display(Name = "Cart ID")]
        public int cartId { get; set; }

        
        [Display(Name = "Checkout Date")]
        public System.DateTime checkoutDate { get; set; }

        [Display(Name = "Quantity Purchased")]
        public int quantityPurchased { get; set; }
        
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }

        public decimal getTotalPrice()
        {
            return Convert.ToDecimal(this.Product.prodPrice * this.quantityPurchased);
        }
    }
}
