//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazadaLatest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductCarts = new HashSet<ProductCart>();
        }

        [Display(Name = "Product ID")]
        public int prodId { get; set; }

        [Required(ErrorMessage = "Product name cannot be empty")]
        [StringLength(maximumLength:30, ErrorMessage = "Product name must be less than 30 characters")]
        [Display(Name = "Product Name")]
        public string prodName { get; set; }

        [Required(ErrorMessage = "Product description cannot be empty")]
        [StringLength(maximumLength: 50, ErrorMessage = "Product name must be less than 50 characters")]
        [Display(Name = "Product Description")]
        public string prodDesc { get; set; }

        [Required(ErrorMessage = "Product price cannot be empty")]
        [Display(Name = "Price (RM)")]
        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = true)]
        public Nullable<double> prodPrice { get; set; }

        [Required(ErrorMessage = "Product quantity cannot be empty")]
        [Display(Name = "Quantity")]
        public int prodQuan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCart> ProductCarts { get; set; }
    }
}
